version: '3'

services:

  chromedriver:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - overlay

  jokebot:
    build: .
    networks:
      - overlay
    entrypoint: python /jokebot/jokebot.py
    depends_on:
      - chromedriver

networks:
  overlay:
